apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    comment.kyaml.io/set.spec.values.image.repository: '{"$imagepolicy": "flux-system:podinfo:name"}'
    comment.kyaml.io/set.spec.values.image.tag: '{"$imagepolicy": "flux-system:podinfo:tag"}'
  name: podinfo
  namespace: default
spec:
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: 5.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: mc1
  annotations:
    comment.kyaml.io/set.spec.containers.[name=1st].image: '{"$imagepolicy": "flux-system:nginx:image"}'
    comment.kyaml.io/set.spec.containers.1.image: '{"$imagepolicy": "flux-system:debian:image"}'
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: 1st
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: 2nd
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date >> /html/index.html; sleep 1; done
